<?php
/**
 * Studioforty9_AjaxAddToCart
 *
 * @category  Studioforty9
 * @package   Studioforty9_AjaxAddToCart
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2016 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/add-to-cart/blob/master/LICENCE BSD
 * @version   0.0.1
 * @link      https://github.com/studioforty9/add-to-cart
 */

/** @var Studioforty9_AjaxAddToCart_Block_Messages_Script $this */
?>
<?php if ($this->isEnabled()): ?>
<script type="text/javascript">
    document.observe("dom:loaded", function() {
        $$('#product_addtocart_form .btn-cart').each(function (el) {
            if (typeof el.readAttribute('onclick') != 'null') {
                el.writeAttribute('onclick', '');
            }
        });
        ajaxAddToCart = new ajaxAddToCartCore('.btn-cart', $('product_addtocart_form'));
    });
</script>
<?php endif; ?>
