<?php
/**
 * Studioforty9_AjaxAddToCart
 *
 * @category  Studioforty9
 * @package   Studioforty9_AjaxAddToCart
 * @author    StudioForty9 <info@studioforty9.com>
 * @copyright 2016 StudioForty9 (http://www.studioforty9.com)
 * @license   https://github.com/studioforty9/add-to-cart/blob/master/LICENCE BSD
 * @version   0.0.1
 * @link      https://github.com/studioforty9/add-to-cart
 */

/** @var Studioforty9_AjaxAddToCart_Block_Messages_Success $this */
?>
<div id="ajaxaddtocart-message" class="messages clearfix" style="clear:both;">
    <ul class="success-msg">
        <li>
            <div style="padding: 10px;">
                <strong><?php echo $this->__('Added to your basket successfully.') ?></strong>
                <?php if ($this->isConfigurable()): ?>
                <p class="<?php echo $this->getProductType() ?>"><?php echo $this->getSelections() ?></p>
                <?php else: ?>
                <p>&nbsp;</p>
                <?php endif; ?>
                <a href="/checkout/cart/" class="button2 btn-cart"><?php echo $this->__('View Basket') ?></a>
                <a href="/checkout/onepage/" class="button btn-checkout"><?php echo $this->__('Checkout') ?></a>
            </div>
        </li>
    </ul>
</div>
