<div id="ajaxaddtocart-message" class="messages clearfix" style="clear:both;">
    <ul class="success-msg">
        <li>
            <div style="padding: 10px;">
                <strong><?php echo $this->__('Added to your basket successfully.') ?></strong>
                <p>&nbsp;</p>
                <a href="/checkout/cart/" class="button2 btn-cart"><?php echo $this->__('View Basket') ?></a>
                <a href="/checkout/onepage/" class="button btn-checkout"><?php echo $this->__('Checkout') ?></a>
            </div>
        </li>
    </ul>
</div>
